[package]
name = "rustcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "vnoj"
path = "src/vnoj/gss.rs"

[dependencies]
cargo-snippet = "0.6.5"
proconio = "0.4.5"
